services:
  # Backend API Service
  - type: web
    name: f1-elo-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1